--Para la creación de tablas:
CREATE TABLE tabla1(
    tabla_id NUMBER GENERATED BY DEFAULT AS IDENTITY,

    --Colocamos las variables que queremos tener:
    nombre_var1 VARCHAR2(50) NOT NULL,
    nombre_var2 VARCHAR2(50) NOT NULL,

    --Colocamos la llave:
    PRIMARY KEY(tabla_id)
);

--Para insertar variables:
INSERT INTO tabla1 (nombre_var1, nombre_var2) values('Valor var 1','Valor var 2')
INSERT INTO tabla1 (nombre_var1, nombre_var2) values('Valor var 1','Valor var 2')
INSERT INTO tabla1 (nombre_var1, nombre_var2) values('Valor var 1','Valor var 2')

--Para mostrar los valores guardados en la tabla:
select from tabla1;