--Para la creación de tablas:
CREATE TABLE tabla1(
    tabla_id NUMBER GENERATED BY DEFAULT AS IDENTITY,

    --Colocamos las variables que queremos tener:
    nombre_var1 VARCHAR2(50) NOT NULL,
    nombre_var2 VARCHAR2(50) NOT NULL,

    --Colocamos la llave:
    PRIMARY KEY(tabla_id)
);

--Para insertar variables:
INSERT INTO tabla1 (nombre_var1, nombre_var2) values('Valor var 1','Valor var 2')
INSERT INTO tabla1 (nombre_var1, nombre_var2) values('Valor var 1','Valor var 2')
INSERT INTO tabla1 (nombre_var1, nombre_var2) values('Valor var 1','Valor var 2')

--Para mostrar los valores guardados en la tabla:
select from tabla1;


--Ahora bien, para el método GET usamos lo siguiente:



--Para el método POST, generamos el siguiente código:
--Con BEGIN establecemos un segmento de código.
BEGIN
    INSERT INTO tabla1(tabla_id, nombre_var1, nombre_var2)
    --Se suele usar los dos puntos (:) para nombrar cuales atributos vamos a manejar.
    VALUES(:tabla_id, :nombre_var1, :nombre_var2);
    :status_code :=201;
end;